import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Camera, Check, ChevronRight, CircleHelp, Clock3, FileImage, Grid3X3, History, ImagePlus, MoreHorizontal, Plus, RotateCcw, Share2, Trophy, Undo2, X } from "lucide-react";
import { BrowserCardImageParser } from "./ocr";
import { cardIssues, completedRows, createGame, emptyRows, fixtureGame, isFullCard, markedCount, nearestLine, resetMarks, toggleNumber, undoLast } from "./core";
import { getLastGame, listGames, saveGame } from "./db";
import type { Card, Cell, Game, ParsedCard } from "./types";

type View="loading"|"home"|"games"|"verify"|"play";
const parser=new BrowserCardImageParser();
const makeCard=(gameId:string,rows:Cell[][]=emptyRows(),n=1):Card=>({id:crypto.randomUUID(),gameId,label:`Cartón ${n}`,rows});

export default function App(){
 const [view,setView]=useState<View>("loading"),[game,setGame]=useState<Game|null>(null),[games,setGames]=useState<Game[]>([]),[draft,setDraft]=useState<Card[]>([]),[saved,setSaved]=useState(true),[sheet,setSheet]=useState<"numbers"|"menu"|null>(null),[ocr,setOcr]=useState<number|null>(null),[notice,setNotice]=useState("");
 const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{(async()=>{const [last,all]=await Promise.all([getLastGame(),listGames()]);setGames(all);setGame(last||null);setView("home")})()},[]);
 useEffect(()=>{if(!game||view==="loading")return;setSaved(false);const t=setTimeout(async()=>{await saveGame(game);setSaved(true);setGames(await listGames())},120);return()=>clearTimeout(t)},[game]);
 const start=(demo=false)=>{const g=demo?fixtureGame():createGame();setGame(g);setDraft(demo?g.cards:[]);if(demo){setView("play");}else{setView("verify")}};
 const update=(fn:(g:Game)=>Game)=>setGame(g=>g?fn(g):g);
 async function upload(files:FileList|null){if(!files||!game)return;setOcr(0);const found:Card[]=[];for(const file of Array.from(files)){try{const result=await parser.parse(file,setOcr);result.cards.forEach((c:ParsedCard)=>found.push({...c,gameId:game.id,label:`Cartón ${draft.length+found.length+1}`,sourceImageId:result.sourceImageId}));if(result.warnings.length)setNotice(result.warnings[0]);}catch{setNotice("No pudimos leer esa imagen. Puedes introducir el cartón manualmente.");}}setDraft(d=>[...d,...found]);setOcr(null);}
 const confirmCards=()=>{if(!game||!draft.length)return setNotice("Agrega al menos un cartón para continuar.");const bad=draft.flatMap(c=>cardIssues(c.rows));if(bad.length)return setNotice(`Revisa ${bad.length} casillas fuera del rango B‑I‑N‑G‑O.`);setGame({...game,cards:draft,updatedAt:new Date().toISOString()});setView("play")};
 if(view==="loading")return <main className="splash"><div className="logo-ball">B</div><p>Preparando tus cartones…</p></main>;
 if(view==="home")return <main className="home"><header className="brand"><div className="logo-ball">B</div><span>Bingo</span></header><section className="hero"><p className="eyebrow">TUS CARTONES, SIEMPRE CONTIGO</p><h1>Listos para cantar<br/><em>¡Bingo!</em></h1><p>Fotografía tus cartones, revisa los números y juega sin perder una sola marca.</p></section><section className="home-actions"><button className="primary" onClick={()=>start()}><Plus/> Nueva partida <ChevronRight/></button>{game&&<button className="continue" onClick={()=>setView("play")}><span><Clock3/><b>Continuar partida</b><small>{game.name} · {game.calledNumbers.length} marcados</small></span><ChevronRight/></button>}<button className="text-button" onClick={()=>setView("games")}><History/> Mis partidas</button></section><footer><span>Guardado en este dispositivo</span><button onClick={()=>navigator.share?.({title:"Bingo",url:location.href})}><Share2/> Compartir app</button></footer></main>;
 if(view==="games")return <main className="page"><PageHead title="Mis partidas" back={()=>setView("home")}/><div className="games-list">{games.map(g=><button key={g.id} onClick={()=>{setGame(g);setView("play")}}><span className="mini-ball">{g.cards.length}</span><span><b>{g.name}</b><small>{new Intl.DateTimeFormat("es",{dateStyle:"medium",timeStyle:"short"}).format(new Date(g.updatedAt))} · {g.calledNumbers.length} marcados</small></span><ChevronRight/></button>)}{!games.length&&<Empty icon={<History/>} title="Todavía no hay partidas" text="Crea una nueva para empezar."/>}</div><button className="fab" onClick={()=>start()}><Plus/> Nueva partida</button></main>;
 if(view==="verify"&&game)return <main className="page verify"><PageHead title="Verifica tus cartones" back={()=>setView("home")}/><div className="intro"><p>Corrige cualquier número antes de empezar. Cada columna admite su rango de Bingo.</p><div className="ranges"><span>B 1–15</span><span>I 16–30</span><span>N 31–45</span><span>G 46–60</span><span>O 61–75</span></div></div>{draft.map((card,i)=><EditableCard key={card.id} card={card} onChange={rows=>setDraft(d=>d.map(c=>c.id===card.id?{...c,rows}:c))} onDelete={()=>setDraft(d=>d.filter(c=>c.id!==card.id))}/>) }{!draft.length&&<Empty icon={<Camera/>} title="Añade una foto o un cartón" text="El análisis ocurre en tu teléfono. Siempre podrás corregir el resultado."/>}<div className="import-actions"><button onClick={()=>input.current?.click()}><ImagePlus/> Analizar imágenes</button><button onClick={()=>setDraft(d=>[...d,makeCard(game.id,emptyRows(),d.length+1)])}><Grid3X3/> Crear manualmente</button><button onClick={()=>{const g=fixtureGame();setDraft(g.cards.map((c,i)=>({...c,gameId:game.id,label:`Cartón ${i+1}`})));setNotice("Tabla 214 cargada para probar la partida.")}}><CircleHelp/> Usar tabla de prueba</button></div><input ref={input} hidden type="file" accept="image/*" multiple onChange={e=>upload(e.target.files)}/>{ocr!==null&&<div className="ocr"><Camera/><b>Analizando en este dispositivo… {ocr}%</b><div><i style={{width:`${ocr}%`}}/></div></div>}<div className="confirm-bar"><span>{draft.length} {draft.length===1?"cartón":"cartones"}</span><button className="primary" onClick={confirmCards}>Confirmar cartones <Check/></button></div>{notice&&<Toast text={notice} close={()=>setNotice("")}/>}</main>;
 if(view==="play"&&game){const leader=Math.max(...game.cards.map(c=>markedCount(c,game.calledNumbers)),0);return <main className="play"><header className="play-head"><button aria-label="Volver" onClick={()=>setView("home")}><ArrowLeft/></button><div><b>{game.name}</b><small><i/> {saved?"Guardado":"Guardando…"}</small></div><button aria-label="Menú" onClick={()=>setSheet("menu")}><MoreHorizontal/></button></header><div className={`cards-grid count-${game.cards.length}`}>{game.cards.map(card=><BingoCard key={card.id} card={card} called={game.calledNumbers} leader={leader>0&&markedCount(card,game.calledNumbers)===leader} tap={n=>{navigator.vibrate?.(18);update(g=>toggleNumber(g,n))}}/>)}</div>{!game.cards.length&&<Empty icon={<Grid3X3/>} title="Esta partida no tiene cartones" text="Agrégalos desde el menú."/>}<nav className="bottom"><button onClick={()=>update(undoLast)} disabled={!game.history.length}><Undo2/><span>Deshacer</span></button><button onClick={()=>setSheet("numbers")}><span className="number-badge">{game.calledNumbers.length}</span><span>Números</span></button><button onClick={()=>setSheet("menu")}><MoreHorizontal/><span>Menú</span></button></nav>{sheet==="numbers"&&<NumbersSheet game={game} close={()=>setSheet(null)}/>} {sheet==="menu"&&<MenuSheet game={game} close={()=>setSheet(null)} reset={()=>{if(confirm("¿Seguro que quieres borrar todas las marcas de esta partida? Los cartones se conservarán.")){update(resetMarks);setSheet(null)}}} add={()=>{setDraft(game.cards);setSheet(null);setView("verify")}} fresh={()=>{setSheet(null);start()}}/>} </main>};return null;
}

function PageHead({title,back}:{title:string;back:()=>void}){return <header className="page-head"><button onClick={back}><ArrowLeft/></button><h1>{title}</h1><span/></header>}
function Empty({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="empty"><span>{icon}</span><b>{title}</b><p>{text}</p></div>}
function Toast({text,close}:{text:string;close:()=>void}){return <div className="toast"><span>{text}</span><button onClick={close}><X/></button></div>}
function EditableCard({card,onChange,onDelete}:{card:Card;onChange:(r:Cell[][])=>void;onDelete:()=>void}){const set=(r:number,c:number,v:string)=>{const rows=card.rows.map(x=>[...x]);rows[r][c]=r===2&&c===2?null:Number(v)||0;onChange(rows)};return <section className="edit-card"><header><b>{card.label}</b><span>{card.confidence?`${Math.round(card.confidence*100)}% confianza`:"Manual"}</span><button onClick={onDelete}><X/></button></header><div className="edit-grid"><div className="letters">{"BINGO".split("").map(x=><b key={x}>{x}</b>)}</div>{card.rows.map((row,r)=>row.map((v,c)=><label key={`${r}-${c}`} className={!cardIssues([[0]]).length?"":""}>{r===2&&c===2?<button className="free" onClick={()=>set(r,c,"")}>LIBRE</button>:<input inputMode="numeric" value={v||""} min={1} max={75} aria-label={`${"BINGO"[c]} fila ${r+1}`} className={cardIssues(card.rows).includes(`${"BINGO"[c]}${r+1}`)?"invalid":""} onChange={e=>set(r,c,e.target.value)}/>}</label>))}</div></section>}
function BingoCard({card,called,leader,tap}:{card:Card;called:number[];leader:boolean;tap:(n:number)=>void}){const lines=completedRows(card,called),near=nearestLine(card,called),full=isFullCard(card,called);return <article className={`bingo-card ${leader?"leader":""} ${full?"winner":""}`}><header><div><b>{card.label}</b>{leader&&<Trophy/>}</div><span>{markedCount(card,called)}/24</span></header><div className="bingo-letters">{"BINGO".split("").map(x=><b key={x}>{x}</b>)}</div><div className="number-grid">{card.rows.map((row,r)=>row.map((v,c)=>v===null?<span key={`${r}-${c}`} className="free">★</span>:<button key={`${r}-${c}`} onClick={()=>tap(v)} className={called.includes(v)?"called":""} aria-pressed={called.includes(v)}>{v}{called.includes(v)&&<Check/>}</button>))}</div><footer>{full?"¡Cartón completo!":lines?`${lines} línea${lines>1?"s":""} completa${lines>1?"s":""}`:near<=2?`A ${near} de una línea`:"En juego"}</footer></article>}
function Sheet({children,close}:{children:React.ReactNode;close:()=>void}){return <div className="overlay" onClick={close}><section className="sheet" onClick={e=>e.stopPropagation()}><div className="handle"/>{children}</section></div>}
function NumbersSheet({game,close}:{game:Game;close:()=>void}){const [matrix,setMatrix]=useState(false);return <Sheet close={close}><header><div><p className="eyebrow">PARTIDA ACTUAL</p><h2>Números salidos</h2></div><button onClick={close}><X/></button></header><div className="tabs"><button className={!matrix?"active":""} onClick={()=>setMatrix(false)}>En orden</button><button className={matrix?"active":""} onClick={()=>setMatrix(true)}>Matriz 1–75</button></div>{matrix?<div className="matrix">{Array.from({length:75},(_,i)=>i+1).map(n=><span className={game.calledNumbers.includes(n)?"called":""} key={n}>{n}</span>)}</div>:<div className="called-list">{game.history.length?game.history.map((n,i)=><span key={n}><small>{i+1}</small>{n}</span>):<Empty icon={<History/>} title="Ningún número todavía" text="Toca un número en cualquier cartón."/>}</div>}</Sheet>}
function MenuSheet({game,close,reset,add,fresh}:{game:Game;close:()=>void;reset:()=>void;add:()=>void;fresh:()=>void}){return <Sheet close={close}><header><div><p className="eyebrow">{game.name}</p><h2>Opciones de partida</h2></div><button onClick={close}><X/></button></header><div className="menu-list"><button onClick={add}><ImagePlus/><span><b>Agregar cartones</b><small>Foto, archivo o entrada manual</small></span><ChevronRight/></button><button onClick={reset}><RotateCcw/><span><b>Reiniciar marcas</b><small>Conserva todos los cartones</small></span><ChevronRight/></button><button onClick={fresh}><Plus/><span><b>Nueva partida</b><small>La actual permanece guardada</small></span><ChevronRight/></button><button onClick={()=>navigator.share?.({title:"Bingo",url:location.href})}><Share2/><span><b>Compartir aplicación</b><small>Los cartones no se comparten</small></span><ChevronRight/></button></div></Sheet>}
